//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clase5_11_09.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceCalculoContraPrestacionSoap")]
    public interface WebServiceCalculoContraPrestacionSoap {
        
        // CODEGEN: Generating message contract since element name apellido from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuantoCobra", ReplyAction="*")]
        Clase5_11_09.ServiceReference1.CuantoCobraResponse CuantoCobra(Clase5_11_09.ServiceReference1.CuantoCobraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuantoCobra", ReplyAction="*")]
        System.Threading.Tasks.Task<Clase5_11_09.ServiceReference1.CuantoCobraResponse> CuantoCobraAsync(Clase5_11_09.ServiceReference1.CuantoCobraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CuantoCobraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CuantoCobra", Namespace="http://tempuri.org/", Order=0)]
        public Clase5_11_09.ServiceReference1.CuantoCobraRequestBody Body;
        
        public CuantoCobraRequest() {
        }
        
        public CuantoCobraRequest(Clase5_11_09.ServiceReference1.CuantoCobraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CuantoCobraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Clase5_11_09.ServiceReference1.ArrayOfString dias;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal valorMateria;
        
        public CuantoCobraRequestBody() {
        }
        
        public CuantoCobraRequestBody(string apellido, Clase5_11_09.ServiceReference1.ArrayOfString dias, decimal valorMateria) {
            this.apellido = apellido;
            this.dias = dias;
            this.valorMateria = valorMateria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CuantoCobraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CuantoCobraResponse", Namespace="http://tempuri.org/", Order=0)]
        public Clase5_11_09.ServiceReference1.CuantoCobraResponseBody Body;
        
        public CuantoCobraResponse() {
        }
        
        public CuantoCobraResponse(Clase5_11_09.ServiceReference1.CuantoCobraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CuantoCobraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CuantoCobraResult;
        
        public CuantoCobraResponseBody() {
        }
        
        public CuantoCobraResponseBody(string CuantoCobraResult) {
            this.CuantoCobraResult = CuantoCobraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCalculoContraPrestacionSoapChannel : Clase5_11_09.ServiceReference1.WebServiceCalculoContraPrestacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCalculoContraPrestacionSoapClient : System.ServiceModel.ClientBase<Clase5_11_09.ServiceReference1.WebServiceCalculoContraPrestacionSoap>, Clase5_11_09.ServiceReference1.WebServiceCalculoContraPrestacionSoap {
        
        public WebServiceCalculoContraPrestacionSoapClient() {
        }
        
        public WebServiceCalculoContraPrestacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCalculoContraPrestacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculoContraPrestacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculoContraPrestacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Clase5_11_09.ServiceReference1.CuantoCobraResponse Clase5_11_09.ServiceReference1.WebServiceCalculoContraPrestacionSoap.CuantoCobra(Clase5_11_09.ServiceReference1.CuantoCobraRequest request) {
            return base.Channel.CuantoCobra(request);
        }
        
        public string CuantoCobra(string apellido, Clase5_11_09.ServiceReference1.ArrayOfString dias, decimal valorMateria) {
            Clase5_11_09.ServiceReference1.CuantoCobraRequest inValue = new Clase5_11_09.ServiceReference1.CuantoCobraRequest();
            inValue.Body = new Clase5_11_09.ServiceReference1.CuantoCobraRequestBody();
            inValue.Body.apellido = apellido;
            inValue.Body.dias = dias;
            inValue.Body.valorMateria = valorMateria;
            Clase5_11_09.ServiceReference1.CuantoCobraResponse retVal = ((Clase5_11_09.ServiceReference1.WebServiceCalculoContraPrestacionSoap)(this)).CuantoCobra(inValue);
            return retVal.Body.CuantoCobraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Clase5_11_09.ServiceReference1.CuantoCobraResponse> Clase5_11_09.ServiceReference1.WebServiceCalculoContraPrestacionSoap.CuantoCobraAsync(Clase5_11_09.ServiceReference1.CuantoCobraRequest request) {
            return base.Channel.CuantoCobraAsync(request);
        }
        
        public System.Threading.Tasks.Task<Clase5_11_09.ServiceReference1.CuantoCobraResponse> CuantoCobraAsync(string apellido, Clase5_11_09.ServiceReference1.ArrayOfString dias, decimal valorMateria) {
            Clase5_11_09.ServiceReference1.CuantoCobraRequest inValue = new Clase5_11_09.ServiceReference1.CuantoCobraRequest();
            inValue.Body = new Clase5_11_09.ServiceReference1.CuantoCobraRequestBody();
            inValue.Body.apellido = apellido;
            inValue.Body.dias = dias;
            inValue.Body.valorMateria = valorMateria;
            return ((Clase5_11_09.ServiceReference1.WebServiceCalculoContraPrestacionSoap)(this)).CuantoCobraAsync(inValue);
        }
    }
}
