//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clase3_28_08.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebServiceEjercicioBSoap")]
    public interface WebServiceEjercicioBSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar", ReplyAction="*")]
        double Sumar(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SumarAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Restar", ReplyAction="*")]
        double Restar(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Restar", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RestarAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicar", ReplyAction="*")]
        double Multiplicar(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicar", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MultiplicarAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dividir", ReplyAction="*")]
        double Dividir(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dividir", ReplyAction="*")]
        System.Threading.Tasks.Task<double> DividirAsync(double a, double b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceEjercicioBSoapChannel : Clase3_28_08.ServiceReference2.WebServiceEjercicioBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceEjercicioBSoapClient : System.ServiceModel.ClientBase<Clase3_28_08.ServiceReference2.WebServiceEjercicioBSoap>, Clase3_28_08.ServiceReference2.WebServiceEjercicioBSoap {
        
        public WebServiceEjercicioBSoapClient() {
        }
        
        public WebServiceEjercicioBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceEjercicioBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEjercicioBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEjercicioBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Sumar(double a, double b) {
            return base.Channel.Sumar(a, b);
        }
        
        public System.Threading.Tasks.Task<double> SumarAsync(double a, double b) {
            return base.Channel.SumarAsync(a, b);
        }
        
        public double Restar(double a, double b) {
            return base.Channel.Restar(a, b);
        }
        
        public System.Threading.Tasks.Task<double> RestarAsync(double a, double b) {
            return base.Channel.RestarAsync(a, b);
        }
        
        public double Multiplicar(double a, double b) {
            return base.Channel.Multiplicar(a, b);
        }
        
        public System.Threading.Tasks.Task<double> MultiplicarAsync(double a, double b) {
            return base.Channel.MultiplicarAsync(a, b);
        }
        
        public double Dividir(double a, double b) {
            return base.Channel.Dividir(a, b);
        }
        
        public System.Threading.Tasks.Task<double> DividirAsync(double a, double b) {
            return base.Channel.DividirAsync(a, b);
        }
    }
}
