//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clase3_28_08.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.WebServiceEjercicioBParte2Soap")]
    public interface WebServiceEjercicioBParte2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Potencia", ReplyAction="*")]
        double Potencia(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Potencia", ReplyAction="*")]
        System.Threading.Tasks.Task<double> PotenciaAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Raiz", ReplyAction="*")]
        double Raiz(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Raiz", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RaizAsync(double a, double b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceEjercicioBParte2SoapChannel : Clase3_28_08.ServiceReference3.WebServiceEjercicioBParte2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceEjercicioBParte2SoapClient : System.ServiceModel.ClientBase<Clase3_28_08.ServiceReference3.WebServiceEjercicioBParte2Soap>, Clase3_28_08.ServiceReference3.WebServiceEjercicioBParte2Soap {
        
        public WebServiceEjercicioBParte2SoapClient() {
        }
        
        public WebServiceEjercicioBParte2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceEjercicioBParte2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEjercicioBParte2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEjercicioBParte2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Potencia(double a, double b) {
            return base.Channel.Potencia(a, b);
        }
        
        public System.Threading.Tasks.Task<double> PotenciaAsync(double a, double b) {
            return base.Channel.PotenciaAsync(a, b);
        }
        
        public double Raiz(double a, double b) {
            return base.Channel.Raiz(a, b);
        }
        
        public System.Threading.Tasks.Task<double> RaizAsync(double a, double b) {
            return base.Channel.RaizAsync(a, b);
        }
    }
}
