<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:tns="http://tempuri.org/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <s:element name="HelloWorld">
        <s:complexType />
      </s:element>
      <s:element name="HelloWorldResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="HelloWorldResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerReporteGananciasV2">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="fechaDesde" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="fechaHasta" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="idCategoria" type="s:int" />
            <s:element minOccurs="1" maxOccurs="1" name="costoMinimo" type="s:decimal" />
            <s:element minOccurs="1" maxOccurs="1" name="costoMaximo" type="s:decimal" />
            <s:element minOccurs="1" maxOccurs="1" name="ventasMinimas" type="s:decimal" />
            <s:element minOccurs="1" maxOccurs="1" name="ventasMaximas" type="s:decimal" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerReporteGananciasV2Response">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ObtenerReporteGananciasV2Result" type="tns:ArrayOfReporteGananciasV2" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfReporteGananciasV2">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="ReporteGananciasV2" nillable="true" type="tns:ReporteGananciasV2" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ReporteGananciasV2">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="Categoria" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="CantidadVentas" type="s:int" />
          <s:element minOccurs="1" maxOccurs="1" name="UnidadesVendidas" type="s:int" />
          <s:element minOccurs="1" maxOccurs="1" name="VentaTotal" type="s:decimal" />
          <s:element minOccurs="1" maxOccurs="1" name="CostoTotal" type="s:decimal" />
          <s:element minOccurs="1" maxOccurs="1" name="GananciaTotal" type="s:decimal" />
          <s:element minOccurs="1" maxOccurs="1" name="PorcentajeGanancia" type="s:decimal" />
        </s:sequence>
      </s:complexType>
      <s:element name="ObtenerReporteV2PorPeriodo">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="tipoRango" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerReporteV2PorPeriodoResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ObtenerReporteV2PorPeriodoResult" type="tns:ArrayOfReporteGananciasV2" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerReporteV2PorCategoria">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="idCategoria" type="s:int" />
            <s:element minOccurs="0" maxOccurs="1" name="fechaDesde" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="fechaHasta" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerReporteV2PorCategoriaResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ObtenerReporteV2PorCategoriaResult" type="tns:ArrayOfReporteGananciasV2" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerEstadisticasV2">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="tipoRango" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerEstadisticasV2Response">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ObtenerEstadisticasV2Result" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GenerarResumenEjecutivoV2">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="tipoRango" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GenerarResumenEjecutivoV2Response">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GenerarResumenEjecutivoV2Result" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="Ping">
        <s:complexType />
      </s:element>
      <s:element name="PingResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="PingResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="HelloWorldSoapIn">
    <wsdl:part name="parameters" element="tns:HelloWorld" />
  </wsdl:message>
  <wsdl:message name="HelloWorldSoapOut">
    <wsdl:part name="parameters" element="tns:HelloWorldResponse" />
  </wsdl:message>
  <wsdl:message name="ObtenerReporteGananciasV2SoapIn">
    <wsdl:part name="parameters" element="tns:ObtenerReporteGananciasV2" />
  </wsdl:message>
  <wsdl:message name="ObtenerReporteGananciasV2SoapOut">
    <wsdl:part name="parameters" element="tns:ObtenerReporteGananciasV2Response" />
  </wsdl:message>
  <wsdl:message name="ObtenerReporteV2PorPeriodoSoapIn">
    <wsdl:part name="parameters" element="tns:ObtenerReporteV2PorPeriodo" />
  </wsdl:message>
  <wsdl:message name="ObtenerReporteV2PorPeriodoSoapOut">
    <wsdl:part name="parameters" element="tns:ObtenerReporteV2PorPeriodoResponse" />
  </wsdl:message>
  <wsdl:message name="ObtenerReporteV2PorCategoriaSoapIn">
    <wsdl:part name="parameters" element="tns:ObtenerReporteV2PorCategoria" />
  </wsdl:message>
  <wsdl:message name="ObtenerReporteV2PorCategoriaSoapOut">
    <wsdl:part name="parameters" element="tns:ObtenerReporteV2PorCategoriaResponse" />
  </wsdl:message>
  <wsdl:message name="ObtenerEstadisticasV2SoapIn">
    <wsdl:part name="parameters" element="tns:ObtenerEstadisticasV2" />
  </wsdl:message>
  <wsdl:message name="ObtenerEstadisticasV2SoapOut">
    <wsdl:part name="parameters" element="tns:ObtenerEstadisticasV2Response" />
  </wsdl:message>
  <wsdl:message name="GenerarResumenEjecutivoV2SoapIn">
    <wsdl:part name="parameters" element="tns:GenerarResumenEjecutivoV2" />
  </wsdl:message>
  <wsdl:message name="GenerarResumenEjecutivoV2SoapOut">
    <wsdl:part name="parameters" element="tns:GenerarResumenEjecutivoV2Response" />
  </wsdl:message>
  <wsdl:message name="PingSoapIn">
    <wsdl:part name="parameters" element="tns:Ping" />
  </wsdl:message>
  <wsdl:message name="PingSoapOut">
    <wsdl:part name="parameters" element="tns:PingResponse" />
  </wsdl:message>
  <wsdl:portType name="ReportingWSSoap">
    <wsdl:operation name="HelloWorld">
      <wsdl:input message="tns:HelloWorldSoapIn" />
      <wsdl:output message="tns:HelloWorldSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ObtenerReporteGananciasV2">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Obtiene reporte de ganancias V2 con filtros dinámicos avanzados</wsdl:documentation>
      <wsdl:input message="tns:ObtenerReporteGananciasV2SoapIn" />
      <wsdl:output message="tns:ObtenerReporteGananciasV2SoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ObtenerReporteV2PorPeriodo">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Obtiene reporte V2 por período predefinido (acceso rápido)</wsdl:documentation>
      <wsdl:input message="tns:ObtenerReporteV2PorPeriodoSoapIn" />
      <wsdl:output message="tns:ObtenerReporteV2PorPeriodoSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ObtenerReporteV2PorCategoria">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Obtiene reporte V2 filtrado por categoría específica</wsdl:documentation>
      <wsdl:input message="tns:ObtenerReporteV2PorCategoriaSoapIn" />
      <wsdl:output message="tns:ObtenerReporteV2PorCategoriaSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ObtenerEstadisticasV2">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Obtiene estadísticas del reporte V2</wsdl:documentation>
      <wsdl:input message="tns:ObtenerEstadisticasV2SoapIn" />
      <wsdl:output message="tns:ObtenerEstadisticasV2SoapOut" />
    </wsdl:operation>
    <wsdl:operation name="GenerarResumenEjecutivoV2">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Genera resumen ejecutivo completo del reporte V2</wsdl:documentation>
      <wsdl:input message="tns:GenerarResumenEjecutivoV2SoapIn" />
      <wsdl:output message="tns:GenerarResumenEjecutivoV2SoapOut" />
    </wsdl:operation>
    <wsdl:operation name="Ping">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Método de prueba para verificar el funcionamiento del WebService</wsdl:documentation>
      <wsdl:input message="tns:PingSoapIn" />
      <wsdl:output message="tns:PingSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ReportingWSSoap" type="tns:ReportingWSSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="HelloWorld">
      <soap:operation soapAction="http://tempuri.org/HelloWorld" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerReporteGananciasV2">
      <soap:operation soapAction="http://tempuri.org/ObtenerReporteGananciasV2" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerReporteV2PorPeriodo">
      <soap:operation soapAction="http://tempuri.org/ObtenerReporteV2PorPeriodo" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerReporteV2PorCategoria">
      <soap:operation soapAction="http://tempuri.org/ObtenerReporteV2PorCategoria" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerEstadisticasV2">
      <soap:operation soapAction="http://tempuri.org/ObtenerEstadisticasV2" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GenerarResumenEjecutivoV2">
      <soap:operation soapAction="http://tempuri.org/GenerarResumenEjecutivoV2" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Ping">
      <soap:operation soapAction="http://tempuri.org/Ping" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="ReportingWSSoap12" type="tns:ReportingWSSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="HelloWorld">
      <soap12:operation soapAction="http://tempuri.org/HelloWorld" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerReporteGananciasV2">
      <soap12:operation soapAction="http://tempuri.org/ObtenerReporteGananciasV2" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerReporteV2PorPeriodo">
      <soap12:operation soapAction="http://tempuri.org/ObtenerReporteV2PorPeriodo" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerReporteV2PorCategoria">
      <soap12:operation soapAction="http://tempuri.org/ObtenerReporteV2PorCategoria" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerEstadisticasV2">
      <soap12:operation soapAction="http://tempuri.org/ObtenerEstadisticasV2" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GenerarResumenEjecutivoV2">
      <soap12:operation soapAction="http://tempuri.org/GenerarResumenEjecutivoV2" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Ping">
      <soap12:operation soapAction="http://tempuri.org/Ping" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ReportingWS">
    <wsdl:port name="ReportingWSSoap" binding="tns:ReportingWSSoap">
      <soap:address location="http://localhost:55128/ReportingWS.asmx" />
    </wsdl:port>
    <wsdl:port name="ReportingWSSoap12" binding="tns:ReportingWSSoap12">
      <soap12:address location="http://localhost:55128/ReportingWS.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>