<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:tns="http://tempuri.org/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <s:element name="ObtenerGananciasGeneral">
        <s:complexType />
      </s:element>
      <s:element name="ObtenerGananciasGeneralResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ObtenerGananciasGeneralResult" type="tns:ArrayOfReporteGanancias" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfReporteGanancias">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="ReporteGanancias" nillable="true" type="tns:ReporteGanancias" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ReporteGanancias">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="Categoria" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="VentasConEstaCategoria" type="s:int" />
          <s:element minOccurs="1" maxOccurs="1" name="UnidadesTotales" type="s:int" />
          <s:element minOccurs="1" maxOccurs="1" name="PrecioPromedio" type="s:decimal" />
          <s:element minOccurs="1" maxOccurs="1" name="GananciaTotal" type="s:decimal" />
        </s:sequence>
      </s:complexType>
      <s:element name="ObtenerGananciasUltimoMes">
        <s:complexType />
      </s:element>
      <s:element name="ObtenerGananciasUltimoMesResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ObtenerGananciasUltimoMesResult" type="tns:ArrayOfReporteGanancias" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerGananciasSemanal">
        <s:complexType />
      </s:element>
      <s:element name="ObtenerGananciasSemanalResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ObtenerGananciasSemanalResult" type="tns:ArrayOfReporteGanancias" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerEstadisticasGanancias">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="tipoReporte" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerEstadisticasGananciasResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ObtenerEstadisticasGananciasResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerCategoriaLider">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="tipoReporte" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ObtenerCategoriaLiderResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ObtenerCategoriaLiderResult" type="tns:ReporteGanancias" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="Ping">
        <s:complexType />
      </s:element>
      <s:element name="PingResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="PingResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="ObtenerGananciasGeneralSoapIn">
    <wsdl:part name="parameters" element="tns:ObtenerGananciasGeneral" />
  </wsdl:message>
  <wsdl:message name="ObtenerGananciasGeneralSoapOut">
    <wsdl:part name="parameters" element="tns:ObtenerGananciasGeneralResponse" />
  </wsdl:message>
  <wsdl:message name="ObtenerGananciasUltimoMesSoapIn">
    <wsdl:part name="parameters" element="tns:ObtenerGananciasUltimoMes" />
  </wsdl:message>
  <wsdl:message name="ObtenerGananciasUltimoMesSoapOut">
    <wsdl:part name="parameters" element="tns:ObtenerGananciasUltimoMesResponse" />
  </wsdl:message>
  <wsdl:message name="ObtenerGananciasSemanalSoapIn">
    <wsdl:part name="parameters" element="tns:ObtenerGananciasSemanal" />
  </wsdl:message>
  <wsdl:message name="ObtenerGananciasSemanalSoapOut">
    <wsdl:part name="parameters" element="tns:ObtenerGananciasSemanalResponse" />
  </wsdl:message>
  <wsdl:message name="ObtenerEstadisticasGananciasSoapIn">
    <wsdl:part name="parameters" element="tns:ObtenerEstadisticasGanancias" />
  </wsdl:message>
  <wsdl:message name="ObtenerEstadisticasGananciasSoapOut">
    <wsdl:part name="parameters" element="tns:ObtenerEstadisticasGananciasResponse" />
  </wsdl:message>
  <wsdl:message name="ObtenerCategoriaLiderSoapIn">
    <wsdl:part name="parameters" element="tns:ObtenerCategoriaLider" />
  </wsdl:message>
  <wsdl:message name="ObtenerCategoriaLiderSoapOut">
    <wsdl:part name="parameters" element="tns:ObtenerCategoriaLiderResponse" />
  </wsdl:message>
  <wsdl:message name="PingSoapIn">
    <wsdl:part name="parameters" element="tns:Ping" />
  </wsdl:message>
  <wsdl:message name="PingSoapOut">
    <wsdl:part name="parameters" element="tns:PingResponse" />
  </wsdl:message>
  <wsdl:portType name="ReportingWebServiceSoap">
    <wsdl:operation name="ObtenerGananciasGeneral">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Obtiene el reporte de ganancias general por todas las categorías</wsdl:documentation>
      <wsdl:input message="tns:ObtenerGananciasGeneralSoapIn" />
      <wsdl:output message="tns:ObtenerGananciasGeneralSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ObtenerGananciasUltimoMes">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Obtiene el reporte de ganancias del último mes (30 días) por categorías</wsdl:documentation>
      <wsdl:input message="tns:ObtenerGananciasUltimoMesSoapIn" />
      <wsdl:output message="tns:ObtenerGananciasUltimoMesSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ObtenerGananciasSemanal">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Obtiene el reporte de ganancias semanal (7 días) por categorías</wsdl:documentation>
      <wsdl:input message="tns:ObtenerGananciasSemanalSoapIn" />
      <wsdl:output message="tns:ObtenerGananciasSemanalSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ObtenerEstadisticasGanancias">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Obtiene estadísticas resumidas de ganancias por tipo de reporte</wsdl:documentation>
      <wsdl:input message="tns:ObtenerEstadisticasGananciasSoapIn" />
      <wsdl:output message="tns:ObtenerEstadisticasGananciasSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ObtenerCategoriaLider">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Obtiene la categoría con mayor ganancia según el tipo de reporte</wsdl:documentation>
      <wsdl:input message="tns:ObtenerCategoriaLiderSoapIn" />
      <wsdl:output message="tns:ObtenerCategoriaLiderSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="Ping">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Método de prueba para verificar el funcionamiento del WebService</wsdl:documentation>
      <wsdl:input message="tns:PingSoapIn" />
      <wsdl:output message="tns:PingSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ReportingWebServiceSoap" type="tns:ReportingWebServiceSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="ObtenerGananciasGeneral">
      <soap:operation soapAction="http://tempuri.org/ObtenerGananciasGeneral" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerGananciasUltimoMes">
      <soap:operation soapAction="http://tempuri.org/ObtenerGananciasUltimoMes" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerGananciasSemanal">
      <soap:operation soapAction="http://tempuri.org/ObtenerGananciasSemanal" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerEstadisticasGanancias">
      <soap:operation soapAction="http://tempuri.org/ObtenerEstadisticasGanancias" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerCategoriaLider">
      <soap:operation soapAction="http://tempuri.org/ObtenerCategoriaLider" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Ping">
      <soap:operation soapAction="http://tempuri.org/Ping" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="ReportingWebServiceSoap12" type="tns:ReportingWebServiceSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="ObtenerGananciasGeneral">
      <soap12:operation soapAction="http://tempuri.org/ObtenerGananciasGeneral" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerGananciasUltimoMes">
      <soap12:operation soapAction="http://tempuri.org/ObtenerGananciasUltimoMes" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerGananciasSemanal">
      <soap12:operation soapAction="http://tempuri.org/ObtenerGananciasSemanal" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerEstadisticasGanancias">
      <soap12:operation soapAction="http://tempuri.org/ObtenerEstadisticasGanancias" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ObtenerCategoriaLider">
      <soap12:operation soapAction="http://tempuri.org/ObtenerCategoriaLider" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Ping">
      <soap12:operation soapAction="http://tempuri.org/Ping" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ReportingWebService">
    <wsdl:port name="ReportingWebServiceSoap" binding="tns:ReportingWebServiceSoap">
      <soap:address location="http://localhost:8081/ReportingWebService.asmx" />
    </wsdl:port>
    <wsdl:port name="ReportingWebServiceSoap12" binding="tns:ReportingWebServiceSoap12">
      <soap12:address location="http://localhost:8081/ReportingWebService.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>